name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go stable
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...

      # Comment out acceptance tests for now. We don't have a Slack workspace for testing.
      # - name: Run Acceptance Tests
      #   env:
      #     SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      #   run: make testacc
