---
on: issues
name: Issue triage
jobs:
  markIssuesForTriage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Apply Issue Triage Label
        uses: actions-ecosystem/action-add-labels@v1
        if: github.event.action == 'opened'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: needs-triage
