---
name: Unit Tests
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['**']
  workflow_call:
jobs:
  unit-tests:
    name: Run Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install dependencies
        run: go mod download
      - name: Run unit tests (excluding acceptance tests)
        run: |
          mkdir -p test-results
          go test ./slack/... -v -short -run "^Test[^A]" 2>&1 | tee test-results/unit-tests.log
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: test-results/unit-tests.log
